spring:
  profiles:
    active:
     - dev
---
spring:
  profiles: dev
  application:
    name: dev11111111111
server:
  port: 3355
a:
 b: dev
eureka:
  instance:
    hostname: localhost
    instance-id: customer-client-${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/
---
spring:
  profiles: test
  application:
    name: test11111111111
server:
  port: 3366
a:
 b: test
eureka:
  instance:
    hostname: localhost
    instance-id: customer-client-${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/
